### ISSUE TITLE
Create a MVP React App That Uses the ShapeShift API

### ISSUE THREAD

**Issue by bountyone** [BountyOneBounties/Issues#12]
We are looking for someone to create a minimum viable product app with React (preferably Create React App) that allows users to ShapeShift their tokens through the ShapeShift API.
There should be a drop-down that allows users to select the token and the tokens that they want to convert them too.
It should show them how much they will receive as well.
Functionality is more important than UI.

**Comment by jules** [comment]
Hey! I've quickly put together a really bland, and hopefully completely functioning app. I'm pretty sure all the listed functionalities are included, but let me know if I missed something!

The repo is here: https://github.com/julesdesmit/bountyone-shapeshiftmvp

And my address: 0x3323E8C6AbCDad7e44554c600e97b141DF0803cd

**Comment by thebkr7** [comment]
@julesdesmit Awesome! I'll review the app today

**Comment by jules** [comment]
@thebkr7 Yo, just checking, did I get the bounty? The issue's closed but I didn't see anything appear in my wallet 😅

**Comment by thebkr7** [comment]
We are in the middle of transitioning over to a more robust smart contract and should it have it up and running for Monday/Tuesday. You should see the funds by then. I apologize for any inconvenience.

**Comment by jules** [comment]
No prob, thanks for letting me know!

**Comment by thebkr7** [comment]
@julesdesmit Great work! ETH is on its way 👍
