### ISSUE TITLE
Job Board Solidity Smart Contract

### ISSUE THREAD

**Issue by thebkr7** [BountyOneBounties/Issues#3]
We would like a smart contract designed for a new section of BountyOne. It will allow users/companies to pay any ERC20 compatible token to the contract and then the contract will record the amount and the address that it came from. The goal here is to have a premium jobs board were companies pay $x to post a job. The contract then forwards the tokens to a specific wallet (this address will not change).

Requirments:
1. Accept and record the amount of ERC20 tokens sent by a user in an array
2. Timestamp when it was created
3. Forward those tokens to a specific address.

**Comment by jules** [comment]
So, the contract itself will be quite simple. It's going to take some synergy with the web application to really make it work, but it's gonna be as follows (with my contract):

1. Have the paying client trigger an approve() call on the token contract of their choice. The spender address should be the deployed smart contract handling tokens.

2. Have the web application handling their payment make a receive() call on the token handler smart contract from the client's ETH address. It has to log the appropriate token contract address beforehand and supply it as an argument.

3. The token handler contract will then set up an interface with that token contract, to check how many tokens are allowed to be withdrawn, and then withdraw them the previously declared forwarding address

4. The information will be logged into a custom struct called User, and this struct will be passed into an array of users.

I've written up a very simple contract handling this stuff. There is also a small function to retrieve the info items at a certain index in the array, called with inquire() and passing the index integer as a value.

Code:
```solidity
pragma solidity ^0.4.21;

contract TokenHandler {
    // Defining all the data types needed to store necessary info.
    struct User {
        uint amount;
        address from;
        uint timestamp;
    }
    address public forward;
    User[] public users;

    // Upon creation, denote the wallet address that tokens will need to be forwarded to.
    function TokenHandler(address _forward) public {
        forward = _forward;
    }

    function receive(address tokenContract) public {
        // Set up an interface with the token contract of choice.
        EIP20Interface c = EIP20Interface(tokenContract);
        // Make sure the user sent some amount of tokens.
        require(c.allowance(msg.sender, this) > 0);
        uint amountOfTokens = c.allowance(msg.sender, this);
        // Transfer the tokens to the forwarding address
        require(c.transferFrom(msg.sender, forward, amountOfTokens));
        // Lastly, log all the info and push it into an array.
        User memory newUser = User({
            amount:amountOfTokens,
            from:msg.sender,
            timestamp:now
        });
        users.push(newUser);
    }

    // Simple function to get desired user info at a certain array index.
    function inquire(uint index) public view returns(uint, address, uint) {
        return (
            users[index].amount,
            users[index].from,
            users[index].timestamp
        );
    }
}


contract EIP20Interface {
    uint256 public totalSupply;
    function balanceOf(address _owner) public view returns (uint256 balance);
    function transfer(address _to, uint256 _value) public returns (bool success);
    function transferFrom(address _from, address _to, uint256 _value) public returns (bool success);
    function approve(address _spender, uint256 _value) public returns (bool success);
    function allowance(address _owner, address _spender) public view returns (uint256 remaining);

    event Transfer(address indexed _from, address indexed _to, uint256 _value);
    event Approval(address indexed _owner, address indexed _spender, uint256 _value);
}
```

I hope that solves it! If there's any errors or things to be appended let me know :)

(Coming from BountyOne just FYI, address is 0x3323E8C6AbCDad7e44554c600e97b141DF0803cd !)

Edit: Removed some oversights.

**Comment by Ameerrosic** [comment]
@thebkr7 anyupdate on this?

**Comment by bountyone** [comment]
@julesdesmit You have completed the bounty and should receive the ether shortly. Nice work!

**Comment by jules** [comment]
@bountyone Seems the transaction has messed up somehow 
![schermafbeelding 2018-05-22 om 21 09 32](https://user-images.githubusercontent.com/30194392/40384654-8120c3da-5e04-11e8-969b-bbdeb4b1ff66.png)

**Comment by thebkr7** [comment]
@julesdesmit I will look into it. I know that Ethereum has been bogged down lately.
