### ISSUE TITLE
An App that Checks the Originality of White Papers

### ISSUE THREAD

**Issue by bountyone** [BountyOneBounties/Issues#4]
We are looking for an application that will scrape sites or a database for white papers and then check their originality through any service. It will then rank the companies with whitepapers based on the percent of plagiarised work.

**Comment by farhan711** [comment]
@bountyone let me know how to start. 
Thanks.

**Comment by thebkr7** [comment]
@farhan711 The rewards are paid out based on work completed. Post back here when you are done with a link to your work.

**Comment by calchulus** [comment]
I'm happy to jump in on this. 
https://github.com/calchulus/Whitepapers-pdfs is a repo I've populated with a few hundred PDFs. Will work on this today.

**Comment by Ameerrosic** [comment]
@calchulus Looking forward to it

**Comment by roschler** [comment]
Not looking for the reward but wanted to comment.  Why not use Google Scholar's plagiarism checker or one of the plagiarism checker's based on it on the web?  Also, if the user doesn't have the Metamask extension installed when they visit Bountyone.io and click "Start Work", nothing happens, at least not on Chrome.  Might be good to put up an error message when the WebSocket connection to localhost:8546 fails (saw that error in the Chrome Debugger console).

**Comment by calchulus** [comment]
Robert could you link us?
And nice suggestion on the metamask!  





On Tue, May 22, 2018 7:48 AM, Robert Oschler notifications@github.com  wrote:
Not looking for the reward but wanted to comment. Why not use Google Scholar's
plagiarism checker or one of the plagiarism checker's based on it on the web?
Also, if the user doesn't have the Metamask extension installed when they visit
Bountyone.io and click "Start Work", nothing happens, at least not on Chrome.
Might be good to put up an error message when the WebSocket connection to
localhost:8546 fails (saw that error in the Chrome Debugger console).

**Comment by roschler** [comment]
Hi Calvin,

I'm not associated with these sites in any way, but for example, this site claims to check papers against Google Scholar and many other sources:

https://copyleaks.com/blog/check-paper-plagiarism/

This article talks about Google Scholar, Copyscape, and several other plagiarism tools:

https://www.plagiarismtoday.com/2010/02/09/5-reasons-google-is-my-primary-plagiarism-checker/

**Comment by calchulus** [comment]
yeah so I tried using some of them, those that have  APIs that are closed off
or limited to a small amount of use, where as we'd like to ideally go through
lots of papers .
The others would require a copy and paste job and scraping, which would be more
time consuming IMO, but happy to take suggestions on a way around any of them.  





On Tue, May 22, 2018 9:43 AM, Robert Oschler notifications@github.com  wrote:
Hi Calvin,

I'm not associated with these sites in any way, but for example, this site
claims to check papers against Google Scholar and many other sources:

https://copyleaks.com/blog/check-paper-plagiarism/

This article talks about Google Scholar, Copyscape, and several other plagiarism
tools:

https://www.plagiarismtoday.com/2010/02/09/5-reasons-google-is-my-primary-plagiarism-checker/

**Comment by farhan711** [comment]
As I already work with on product [RAx](https://raxter.io/) It searches your research and in the result, it gives similar research if found. So its type of plagiarism checker but it searches entire internet (scrap the data) and generates output.

**Comment by speedrunn** [comment]
So, you need a working application, yea?
(I think, i know how to make it)

**Comment by calchulus** [comment]
to give an update, I'm working w/ these tools, as well as my own similarity
score measure using python natural language processing toolkit
https://github.com/ieeecompsoc/Plagiarism-Checker
https://github.com/architshukla/Plagiarism-Checker  





On Wed, May 23, 2018 9:07 AM, speedrunn notifications@github.com  wrote:
So, you need a working application, yea?
(I think, i know how to make it)

**Comment by speedrunn** [comment]
@bountyone @thebkr7 
App is ready. But  there are no free service who has api and which can check more than 10k symbols per request, so you need to pay around 5$ for 600 000 symbols. Are you ok with that?

**Comment by thebkr7** [comment]
@speedrunn What service are you thinking of using?

**Comment by speedrunn** [comment]
@thebkr7 text.ru
For example copyleaks wanna 8$/month for  25K words / month, as text.ru only 5$ for 600K words.

**Comment by DoctorRV** [comment]
@speedrunn you can probably break down the checks into blocks of 10k characters and check and repeat until it reaches the end of the whitepaper.

**Comment by speedrunn** [comment]
@DoctorRV any api wanna some $ for using, so.
Are you   author of this Task?

**Comment by speedrunn** [comment]
https://github.com/speedrunn/checkWhitePapers
My ETH adress - 0xd092012F7d698e31301832C7be3559a5986c0594

**Comment by tissor** [comment]
https://www.quetext.com/pricing
PRO $9.99/month
Word-limit per Search | 25,000 words (50 pages)

**Comment by speedrunn** [comment]
@tissor but they don't have API.

**Comment by tissor** [comment]
https://www.copyscape.com/api-guide.php

**Comment by tissor** [comment]
https://youtu.be/Vhh_GeBPOhs
0x602C04cE20c66D90ea61aBA9bE8467876A278be6
)))

**Comment by calchulus** [comment]
still minimum 3 cents per search though :/  not particularly scalable when so
many whitepapers exist, as well as different version of yellowpapers, etc.
I'll send some more info later today on my progress.  





On Tue, May 29, 2018 11:14 AM, tissor notifications@github.com  wrote:
https://youtu.be/Vhh_GeBPOhs
0x602C04cE20c66D90ea61aBA9bE8467876A278be6
)))

**Comment by speedrunn** [comment]
Copyscape
From April 2, 2018: Only 3c per search for the first 200 words + 1c per additional 100 words or part thereof.
As i said, text ru has the lowest price on market and i write code for using it.

**Comment by thebkr7** [comment]
@speedrunn Thank you for your submission. We are reviewing it

**Comment by speedrunn** [comment]
@thebkr7 I can add functions, that you can grap text from databases and can send you my userkey with 600k words, so you can work through with all whitepapers.

**Comment by thebkr7** [comment]
@speedrunn @calchulus we are making another bounty to integrate this into a front end app.
@speedrunn Your work has been accepted
